baseURL = "https://azdochistory.aimless.jp/"
title = "Change history of Azure docs"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
relativeURLs = true

[params]
  description = "Change history of Azure docs"
  copyright = "Copyright © 2020 kongou_ae"
  dark = "auto"
  highlight = true

[outputs]
home = [ "HTML", "RSS" ]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
